sac_opt_1:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_opt.yaml
  -hp: hyperparameters/sac_opt.yaml
sac_opt_2:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_opt.yaml
  -hp: hyperparameters/sac_opt.yaml
sac_opt_3:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_opt.yaml
  -hp: hyperparameters/sac_opt.yaml
sac_opt_4:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_opt.yaml
  -hp: hyperparameters/sac_opt.yaml
sac_opt_5:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_opt.yaml
  -hp: hyperparameters/sac_opt.yaml
sac_sb3_1:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_sb3.yaml
  -hp: hyperparameters/sac_sb3.yaml
sac_sb3_2:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_sb3.yaml
  -hp: hyperparameters/sac_sb3.yaml
sac_sb3_3:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_sb3.yaml
  -hp: hyperparameters/sac_sb3.yaml
sac_sb3_4:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_sb3.yaml
  -hp: hyperparameters/sac_sb3.yaml
sac_sb3_5:
  -a: sac
  -e: 500000
  -r: success_time_and_distance
  -s: models/sac_sb3.yaml
  -hp: hyperparameters/sac_sb3.yaml
ppo_opt_1:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_opt.yaml
  -hp: hyperparameters/ppo_opt.yaml
ppo_opt_2:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_opt.yaml
  -hp: hyperparameters/ppo_opt.yaml
ppo_opt_3:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_opt.yaml
  -hp: hyperparameters/ppo_opt.yaml
ppo_opt_4:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_opt.yaml
  -hp: hyperparameters/ppo_opt.yaml
ppo_opt_5:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_opt.yaml
  -hp: hyperparameters/ppo_opt.yaml
ppo_sb3_1:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_sb3.yaml
  -hp: hyperparameters/ppo_sb3.yaml
ppo_sb3_2:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_sb3.yaml
  -hp: hyperparameters/ppo_sb3.yaml
ppo_sb3_3:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_sb3.yaml
  -hp: hyperparameters/ppo_sb3.yaml
ppo_sb3_4:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_sb3.yaml
  -hp: hyperparameters/ppo_sb3.yaml
ppo_sb3_5:
  -a: ppo
  -e: 500000
  -r: success_time_and_distance
  -s: models/ppo_sb3.yaml
  -hp: hyperparameters/ppo_sb3.yaml
td3_opt_1:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_opt.yaml
  -hp: hyperparameters/td3_opt.yaml
td3_opt_2:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_opt.yaml
  -hp: hyperparameters/td3_opt.yaml
td3_opt_3:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_opt.yaml
  -hp: hyperparameters/td3_opt.yaml
td3_opt_4:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_opt.yaml
  -hp: hyperparameters/td3_opt.yaml
td3_opt_5:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_opt.yaml
  -hp: hyperparameters/td3_opt.yaml
td3_sb3_1:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_sb3.yaml
  -hp: hyperparameters/td3_sb3.yaml
td3_sb3_2:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_sb3.yaml
  -hp: hyperparameters/td3_sb3.yaml
td3_sb3_3:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_sb3.yaml
  -hp: hyperparameters/td3_sb3.yaml
td3_sb3_4:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_sb3.yaml
  -hp: hyperparameters/td3_sb3.yaml
td3_sb3_5:
  -a: td3
  -e: 500000
  -r: success_time_and_distance
  -s: models/td3_sb3.yaml
  -hp: hyperparameters/td3_sb3.yaml